LAM-974 feat: dockerize machine for integration tests
lamassu/lamassu-machine pull request #1043
Opened 2023-10-17 14:43 UTC by RafaelTaranto

2023-10-18 15:24 UTC, siiky requested changes

2023-10-18 15:24 UTC, siiky commented on Dockerfile
> +RUN cp ./mock_data/licenses.sample.json ./licenses.json
licenses are no longer used?

2023-10-18 15:24 UTC, siiky commented on lib/update/updater.js
> +  host: "updates.lamassu.is",
unused..?

2023-10-18 15:24 UTC, siiky commented on build-scripts/build-docker.sh
> +sed -i "s/..\/node_modules\///g"  ui/start-test.html
```
sed 's/app.js/docker-app.js/g; s/..\/node_modules\///g;' ui/start.html > ui/start-docker.html
sed 's/app.js/test-app.js/g; s/..\/node_modules\///g;' ui/start.html > ui/start-test.html
```

2023-10-18 15:24 UTC, siiky commented on deploy/codebase/build.sh
>  cp $MACHINE_DIR/licenses.json $TARGET_MACHINE_DIR
licenses are no longer used?

2023-10-26 10:00 UTC, RafaelTaranto commented on lib/update/updater.js
> +  host: "updates.lamassu.is",
IDK why that was missing, added.

2023-10-27 14:41 UTC, siiky approved these changes

2024-04-15 07:55 UTC, merged