WIP: fix: id003 initialization improvements
lamassu/lamassu-machine pull request #531
Opened 2020-09-15 17:52 UTC by RafaelTaranto

2020-09-17 22:57 UTC, naconner commented
![](https://github.trello.services/images/mini-trello-icon.png) [id003 initialization improvements](https://trello.com/c/Fou4uXnt/136-id003-initialization-improvements)

2020-09-20 12:31 UTC, joshmh commented
What happens if we miss the ENQ response? Since we're not polling, we'll never check the status. Also, it might still be possible to send two commands at the same time, although that does become more unlikely.

It might be simpler to instead have a function that controls all sends and makes sure they are always properly serialized. It could also drop status requests if not enough time has elapsed since the previous command was sent.

2020-09-25 10:03 UTC, joshmh requested changes

2020-09-25 10:03 UTC, joshmh commented on lib/id003/id003.js
> +  clearInterval(this.pollingInterval)
Might as well use ``_stopPolling()`` here.

2020-09-25 20:13 UTC, RafaelTaranto commented on lib/id003/id003.js
> +    if (!this.disablePolling) {
good point.

2020-09-25 20:21 UTC, RafaelTaranto commented on lib/id003/id003.js
> +    if (!this.disablePolling) {
actually since this is a arrow function this can be updated by the time we get here.

2020-09-25 20:27 UTC, merged