fix: 'Shutdown' admin button not shutting down machine
lamassu/lamassu-machine pull request #550
Opened 2020-11-03 17:27 UTC by liordino

feat: created shutdown action

2020-11-03 17:27 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) ['Shutdown' admin button not shutting down machine](https://trello.com/c/4GdLCkw0/320-shutdown-admin-button-not-shutting-down-machine)

2020-11-04 11:31 UTC, RafaelTaranto approved these changes

2020-11-04 13:13 UTC, joshmh requested changes

2020-11-04 13:13 UTC, joshmh commented on lib/brain.js
> +    process.exit(0)
Shouldn't we attempt a more graceful shutdown, like only when the machine is idle?

2020-11-04 17:40 UTC, joshmh commented on lib/brain.js
> +    process.exit(0)
Decided to do this is an separate card.

2020-11-04 17:40 UTC, merged