feat: validate bech32 zec addresses
lamassu/lamassu-machine pull request #555
Opened 2020-11-17 16:42 UTC by naconner

Depends on https://github.com/lamassu/lamassu-server/pull/518

2020-11-18 16:58 UTC, RafaelTaranto approved these changes

2020-11-20 18:22 UTC, joshmh requested changes

2020-11-20 18:22 UTC, joshmh commented on lib/coins/zec.js
> +  if (zecBech32Validator(network, address, bech32Opts)) return true
Need to return ``false`` if the other tests fail. Also do we have a test for failing this validation function? It should have caught that.

2021-03-07 21:23 UTC, RafaelTaranto approved these changes

2021-03-16 19:47 UTC, closed without merging