Feat: Machine will wait for a transaction to finish before shutting down
lamassu/lamassu-machine pull request #559
Opened 2020-11-24 10:46 UTC by csrapr

2020-11-24 10:56 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Shutdown by admin action should be graceful](https://trello.com/c/NuBA46ut/339-shutdown-by-admin-action-should-be-graceful)

2020-11-24 16:01 UTC, RafaelTaranto requested changes

2020-11-24 16:01 UTC, RafaelTaranto commented on lib/brain.js
> +    console.log ("In the middle of a transaction. Will shutdown when it is done...")
How will this shutdown when done? Looks like you are just ignoring the request.

2020-11-25 19:19 UTC, RafaelTaranto approved these changes

2020-12-11 19:21 UTC, merged