Feat: Perform manual scan of ID card photo
lamassu/lamassu-machine pull request #560
Opened 2020-12-08 00:49 UTC by liordino

feat: added a new state for the manual scan of id card photos on sintra

feat: pass the model as argument for compliance tiers

2020-12-08 00:49 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Perform manual scan of ID card photo](https://trello.com/c/aMlBhw7n/197-perform-manual-scan-of-id-card-photo)

2020-12-17 10:23 UTC, jsousa127 approved these changes

2020-12-24 13:48 UTC, RafaelTaranto requested changes

2020-12-24 13:48 UTC, RafaelTaranto commented on ui/main.css
> +.filled-progress-button-bg {
this has to be done on ui/css and build to this file

2020-12-24 13:48 UTC, RafaelTaranto commented on ui/js/app.js
> +  setupButton('ready-to-scan-id-card-photo', 'scanIdCardPhoto');
these changes have to be made on ui/src/app.js and build to this file

2020-12-24 13:48 UTC, RafaelTaranto commented on ui/start.html
> +    <section
has to be changed in the ui/html folder and builded to this file

2021-01-05 18:11 UTC, jsousa127 approved these changes

2021-01-07 09:58 UTC, RafaelTaranto approved these changes

2021-01-18 15:27 UTC, joshmh requested changes

2021-01-18 15:27 UTC, joshmh commented on lib/brain.js
> +      case 'scanPhotoCardSintra':
I think it would be better if this was "scanPhotoCardManual".

2021-01-18 15:27 UTC, joshmh commented on lib/compliance/flows/id-card-photo.js
> +        START_SINTRA: 'scanPhotoCardSintra'
This should also be START_MANUAL.

2021-01-22 08:23 UTC, closed without merging