Integrate lamassu-coins module
lamassu/lamassu-machine pull request #562
Opened 2021-01-05 15:53 UTC by chaotixkilla

2021-01-05 15:54 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create the lamassu-coins package](https://trello.com/c/OwjinDcp/486-create-the-lamassu-coins-package)

2021-01-08 19:15 UTC, jsousa127 approved these changes

2021-02-05 18:31 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [ERC-20: Add USDT](https://trello.com/c/snrPYh1G/549-erc-20-add-usdt)

2021-02-08 16:16 UTC, josepfo approved these changes

2021-06-09 23:09 UTC, RafaelTaranto requested changes

2021-06-09 23:09 UTC, RafaelTaranto commented on lib/brain.js
> +const coinUtils = require('lamassu-coins').utils
```suggestion
const { utils as coinUtils, CRYPTO_CURRENCIES } = require('lamassu-coins')
```

2021-06-09 23:09 UTC, RafaelTaranto commented on lib/brain.js
> +const coinUtils = require('lamassu-coins').utils
Same thing for the rest of the places with the import.

2021-06-10 09:11 UTC, RafaelTaranto approved these changes

2021-06-19 18:48 UTC, merged