Fix wallet address format case sensitive
lamassu/lamassu-machine pull request #567
Opened 2021-01-14 15:17 UTC by chaotixkilla

2021-01-14 15:17 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Wallet address format case sensitive (bech32)](https://trello.com/c/Q7XXgh4y/475-wallet-address-format-case-sensitive-bech32)

2021-01-15 14:49 UTC, csrapr requested changes

2021-01-15 14:49 UTC, csrapr commented on lib/coins/btc.js
> +  const res = /^(bitcoin:\/{0,2})?(\w+)/i.exec(url)
check if it's necessary to allow between 0 and 2 forward slashes between the first capture group and the second

2021-01-18 14:45 UTC, csrapr approved these changes

2021-01-18 17:47 UTC, RafaelTaranto requested changes
Why are the app.js files being changed here? lib/coins/btc.js should only be used by the nodejs part of the code. remove the builded changes.

2021-01-18 18:53 UTC, RafaelTaranto approved these changes

2021-01-18 20:25 UTC, merged