Parse BCID cards
lamassu/lamassu-machine pull request #573
Opened 2021-01-28 17:27 UTC by chaotixkilla

2021-01-28 17:42 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [ID Data does not parse British Columbia bar codes](https://trello.com/c/PLlgeQ9j/536-id-data-does-not-parse-british-columbia-bar-codes)

2021-01-28 21:09 UTC, csrapr approved these changes

2021-01-28 21:20 UTC, csrapr requested changes
The person in the example code weighs 95 pounds, but what if they weighed 195 pounds?
I tested the code and the output is this: `weight: "19"` (notice how it is ignoring the trailing 5)
Also if the weight is 195 the eye color becomes "NBL"

try testing here:
https://npm.runkit.com/lodash
https://paste.ofcode.org/32KtvRjtPtrJhtCFdkBGA3f

2021-01-28 21:33 UTC, csrapr approved these changes

2021-02-02 10:21 UTC, RafaelTaranto requested changes

2021-02-02 10:21 UTC, RafaelTaranto commented on lib/compliance/parsepdf417.js
> +  require('./parsepdf417-ca-bc'),
isn't it better to check for us first?

2021-02-02 15:23 UTC, RafaelTaranto approved these changes

2021-02-03 23:11 UTC, joshmh requested changes

2021-02-03 23:11 UTC, joshmh commented on lib/compliance/parsepdf417-ca-bc.js
> +  const track1Start = data.indexOf('%')
We shouldn't do these searches twice. If we merge parse and parseRaw, the combined function is just one line longer than parseRaw (the ``if`` statement).

2021-02-04 13:23 UTC, merged