Standardize country codes to alpha-2
lamassu/lamassu-machine pull request #576
Opened 2021-02-02 20:21 UTC by chaotixkilla

2021-02-02 20:23 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Standardize country codes to follow ISO 3166-1 alpha-2](https://trello.com/c/KHOCElKU/542-standardize-country-codes-to-follow-iso-3166-1-alpha-2)

2021-02-03 20:23 UTC, csrapr requested changes

2021-02-03 20:23 UTC, csrapr commented on lib/compliance/parsepdf417.js
> +    console.log(r)
stray console log

2021-02-08 22:30 UTC, csrapr commented
I think it's worth it to squash 4fa1fbb into f987131

2021-02-09 10:34 UTC, RafaelTaranto approved these changes

2021-02-14 23:29 UTC, merged