Verify customer suspend state when tx
lamassu/lamassu-machine pull request #577
Opened 2021-02-05 17:28 UTC by josepfo

2021-02-05 17:34 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) ["Suspend" state not showing on admin](https://trello.com/c/vee9n3T2/527-suspend-state-not-showing-on-admin)

2021-02-08 12:50 UTC, chaotixkilla approved these changes
Seems good, really like the JSDoc comments. Perhaps it is something we should be doing more

2021-02-08 15:59 UTC, RafaelTaranto approved these changes

2021-02-08 15:59 UTC, RafaelTaranto commented on lib/brain.js
> +Brain.prototype.isSuspended = function isSuspended (customer, now) {
I don't see a reason why now is a param, can't we just create a new Date within this function?

2021-02-08 15:59 UTC, RafaelTaranto commented on lib/brain.js
> +Brain.prototype.showSuspendedCustomer = function showSuspendedCustomer (customer, now) {
Same as above

2021-02-08 16:01 UTC, RafaelTaranto requested changes

2021-02-08 16:01 UTC, RafaelTaranto commented on lib/brain.js
> +Brain.prototype.hardLimitReached = function hardLimitReached (customer, now) {
Can we rename this? By the name looks like we're testing for a boolean. 

Maybe `getHardLimitReachedData`

2021-02-08 16:43 UTC, RafaelTaranto approved these changes

2021-02-14 23:03 UTC, merged