Reject expired IDs
lamassu/lamassu-machine pull request #579
Opened 2021-02-09 20:16 UTC by chaotixkilla

2021-02-09 20:17 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Reject expired IDs](https://trello.com/c/TXOi8uy4/565-reject-expired-ids)

2021-02-10 10:38 UTC, josepfo requested changes

2021-02-10 10:38 UTC, josepfo commented on lib/brain.js
> +      console.log('Expired ID card')
If this console.log isn't needed remove it and move this to Rafa's

2021-02-10 12:41 UTC, josepfo approved these changes

2021-02-11 10:33 UTC, RafaelTaranto requested changes

2021-02-11 10:33 UTC, RafaelTaranto commented on lib/brain.js
> +  const now = Date.now()
Isn't this a issue for cards that are expiring on the month of the tx?

2021-02-11 10:33 UTC, RafaelTaranto commented on lib/compliance/parsepdf417-us.js
> +    result.expirationYear = expirationDate ? expirationDate.substr(4, 4) : '00'
Can't we just use the current expirationDate to perform the test? We don't really need to create the additional fields.

2021-02-11 14:35 UTC, RafaelTaranto approved these changes

2021-02-15 23:14 UTC, joshmh requested changes

2021-02-15 23:14 UTC, joshmh commented on lib/brain.js
> +  if (cardData.country === 'ZA') return false
Explain why we're returning false here.

2021-02-16 15:26 UTC, merged