Lowercasing bech32 addresses
lamassu/lamassu-machine pull request #580
Opened 2021-02-10 16:44 UTC by chaotixkilla

2021-02-10 16:44 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Set bech32 all-caps addresses to lowercase](https://trello.com/c/1OEKXHTX/569-set-bech32-all-caps-addresses-to-lowercase)

2021-02-12 10:24 UTC, josepfo approved these changes

2021-02-12 10:38 UTC, RafaelTaranto approved these changes

2021-02-15 23:07 UTC, joshmh requested changes

2021-02-15 23:07 UTC, joshmh commented on lib/coins/btc.js
> +  return isBech32Address(address, bech32Opts)
This should be generalized more. We need a new ``formatAddress`` function that takes an address and lowercases it when necessary.

2021-02-16 19:10 UTC, merged