Fix: fix QR code not reading
lamassu/lamassu-machine pull request #593
Opened 2021-03-11 18:46 UTC by csrapr

2021-03-11 18:46 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bitpay QR code not scanning](https://trello.com/c/2Iya7581/511-bitpay-qr-code-not-scanning)

2021-03-15 15:02 UTC, chaotixkilla requested changes

2021-03-15 15:02 UTC, chaotixkilla commented on package.json
> +    "@joepie91/v4l2camera": "^1.0.5",
On line `49`, there's the same dependency, but on another version and possibly repo. Check with Rafael whether that optionalDependency should be removed or not and if it is worth for us to create our own fork of the v412camera repository

2021-03-15 19:38 UTC, chaotixkilla approved these changes

2021-03-28 20:12 UTC, RafaelTaranto approved these changes

2021-05-22 17:12 UTC, merged