fix: escape double quotes and keep html tags
lamassu/lamassu-machine pull request #613
Opened 2021-04-29 08:50 UTC by josepfo

2021-04-29 08:51 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix translation file generation](https://trello.com/c/jp8flnlV/718-fix-translation-file-generation)

2021-05-06 13:35 UTC, chaotixkilla approved these changes

2021-05-14 10:34 UTC, RafaelTaranto requested changes

2021-05-14 10:34 UTC, RafaelTaranto commented on i18n/ui/lbm-ui_en-US.po
> +
Hehe, you just found a bug on the limit-reached screen. i18n tag should be on the inner div.

2021-05-14 10:34 UTC, RafaelTaranto commented on i18n/ui/lbm-ui_en-US.po
> +msgid "<strong>We'll be up in a moment.</strong>"
Having the tags on the ID should change what's translatable based on the locales.js file. Can you verify that this string gets translated to another language?

2021-06-09 23:04 UTC, closed without merging