Fix: translation file generation
lamassu/lamassu-machine pull request #629
Opened 2021-06-09 20:34 UTC by josepfo

2021-06-09 20:34 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix translation file generation](https://trello.com/c/jp8flnlV/718-fix-translation-file-generation)

2021-06-09 23:04 UTC, RafaelTaranto requested changes

2021-06-09 23:04 UTC, RafaelTaranto commented on ui/html/limit-reached.html
> +      class="filled-progress-button button ok"
The js-i18n should be on the inner div, here we're not translating this button at all.

2021-06-10 20:26 UTC, RafaelTaranto approved these changes

2021-06-17 16:59 UTC, merged