feat: add cash-in dynamic crypto units display
lamassu/lamassu-machine pull request #634
Opened 2021-06-26 21:46 UTC by josepfo

2021-06-26 21:47 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Operator choice of machine-displayed crypto units](https://trello.com/c/ytcgzrUz/833-operator-choice-of-machine-displayed-crypto-units)

2021-07-06 00:28 UTC, chaotixkilla approved these changes

2021-07-23 11:43 UTC, RafaelTaranto requested changes

2021-07-23 11:43 UTC, RafaelTaranto commented on ui/src/app.js
> +  var decimalPlaces = (coin.displayScale - coin.unitScale) + 6
Add a comment explaining this one.

2021-07-23 11:43 UTC, RafaelTaranto commented on lib/brain.js
> +    const { displayScale, displayCode } = _.get(`units.${unitSelected}`)(coinSettings)
Maybe we could default to the first available unit.

2021-11-14 23:13 UTC, merged