Feat/arbitrary compliance choice list
lamassu/lamassu-machine pull request #639
Opened 2021-07-08 14:46 UTC by csrapr

2021-07-08 14:48 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Custom requirements - list](https://trello.com/c/U52YgpVe/817-custom-requirements-list)

2021-07-09 14:57 UTC, chaotixkilla requested changes

2021-07-09 14:57 UTC, chaotixkilla commented on lib/brain.js
> +  this._transitionState(appState, { context: 'compliance', ...customInfoRequest })
Not the biggest fan of using spread on a possible null value, but it works

2021-07-09 14:57 UTC, chaotixkilla commented on lib/brain.js
> +      return true
My logic might be faulty, but can't this be simplified to:

```suggestion
      return !!customerData && customerData.approved !== false
```

2021-07-09 14:57 UTC, chaotixkilla commented on lib/brain.js
> +  const requiredTiers = _.sortBy(name => uuid.validate(name) ? Infinity : _.indexOf(name, ORDERED_REQUIREMENTS))(unorderedTiers)
Doesn't this lead to a scenario where custom triggers 'draw' on the sorting function and custom triggers being unordered between themselves? It's this is not an important scenario, just ignore it

2021-07-09 14:57 UTC, chaotixkilla commented on ui/js/choice-list.js
> +}
```suggestion
  this.selectedChoices.length === 0
    ? this.choiceList.find('.submit-choice-list-button')[0].disabled = true
    : this.choiceList.find('.submit-choice-list-button')[0].disabled = false
}
```

2021-07-09 14:57 UTC, chaotixkilla commented on ui/js/choice-list.js
> +  // this.choiceList.find('.choice-list-arrow-up').hide()
You can remove this maybe?

2021-07-09 14:57 UTC, chaotixkilla commented on ui/js/choice-list.js
> +}
Missing /n at EOF

2021-07-09 14:57 UTC, chaotixkilla commented on ui/js/keypad.js
> +  var display = getDisplay(this.result, this.type, this.opts.country, this.opts)
Since you're passing `this.opts` as a parameter now, we can omit the `this.opts.country` and get it inside the `getDisplay()` function

2021-07-09 14:57 UTC, chaotixkilla commented on ui/js/keypad.js
> +  var display = getDisplay(this.result, this.type, this.opts.country, this.opts)
Same here

2021-11-19 10:10 UTC, closed without merging