feat: register if the manual trigger data is gathered
lamassu/lamassu-machine pull request #643
Opened 2021-07-20 10:27 UTC by josepfo

2021-08-01 21:24 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement the manual option for triggers PT1](https://trello.com/c/2GUd8oIC/840-implement-the-manual-option-for-triggers-pt1)

2021-08-06 01:39 UTC, chaotixkilla requested changes

2021-08-06 01:39 UTC, chaotixkilla commented on lib/brain.js
> +    }
You can refactor all the code related with this to a function I think

```suggestion
    function setManualTrigger (code) {
      if (_.get(code)(this.trader.triggersAutomation) === MANUAL) {
        this.manualTriggersDataProvided[code] = true
      }
    }
```

2021-08-24 03:29 UTC, chaotixkilla requested changes

2021-08-24 03:29 UTC, chaotixkilla commented on lib/brain.js
> +    this.txBlockedByManualTrigger = false
Hmm, if I recall correctly, showing the blocked customer screen always leads to calls to `_idle()`. Is it possible to move this `txBlockedByManualTrigger` reset and all its instances (lines 1978, 2204, 2747) to the `_idle()` function instead? It'll just be called once and it's closer to the other variable resets

2021-09-16 10:29 UTC, RafaelTaranto approved these changes

2021-10-04 10:40 UTC, merged