Feat: add delay on tc screen
lamassu/lamassu-machine pull request #651
Opened 2021-08-06 10:29 UTC by josepfo

2021-08-06 11:32 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add a delay to acceptance of the Terms & Conditions screen](https://trello.com/c/JGL73LUt/905-add-a-delay-to-acceptance-of-the-terms-conditions-screen)

2021-08-24 03:38 UTC, chaotixkilla requested changes

2021-08-24 03:38 UTC, chaotixkilla commented on i18n/ui/lbm-ui_en-US.po
> +msgstr "Please press the front of your state ID card against the scan window, hold it there, and then press "Ready to scan"."
Revert these changes (escaping the `"` char)

2021-08-24 03:38 UTC, chaotixkilla commented on ui/src/app.js
> +const secondsDelayTermsConditions = 7
Doesn't this mean that T&C will always take 7 seconds, independently of what is set on `this.trader.termsDelay`? You are sending the `delay` field on the screen transaction in `brain.js`, but that value is never saved. To do so, add an if statement on the `processData()` function, which is where the data sent from `brain.js` functions is processed

2021-08-30 10:55 UTC, RafaelTaranto approved these changes

2021-09-07 16:21 UTC, merged