feat: send sms receipt
lamassu/lamassu-machine pull request #652
Opened 2021-08-10 19:30 UTC by josepfo

2021-08-10 19:30 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Offer SMS receipt](https://trello.com/c/WS8yKiGu/906-offer-sms-receipt)

2021-08-25 01:14 UTC, chaotixkilla requested changes

2021-08-25 01:14 UTC, chaotixkilla commented on lib/brain.js
> +    receiptStatus: this.trader.receiptPrintingActive ? 'available' : 'disabled',
Any reason for this change? Only thing I could think of is the prettier config with `trailingComma: true`

2021-08-25 01:14 UTC, chaotixkilla commented on lib/brain.js
> +    receiptStatus: this.trader.receiptPrintingActive ? 'available' : 'disabled',
Or, thinking better about this change, seems as a leftover change where you added a field that was later deleted during development

2021-08-25 01:14 UTC, chaotixkilla commented on lib/brain.js
> +    receiptStatus: this.trader.receiptPrintingActive ? 'available' : 'disabled',
Same here

2021-08-25 01:14 UTC, chaotixkilla commented on lib/trader.js
> +    body: { data },
Isn't `data` already an object?

2021-08-25 01:14 UTC, chaotixkilla commented on lib/trader.js
> +    body: { data },
You're accessing this with `req.body.data` on server-side, due to this. Changing this has little to no impact, just pointed it out due to other functions in the trader module sending the object as is, without encapsulating on a `data` field

2021-09-22 08:53 UTC, RafaelTaranto approved these changes

2021-11-17 14:30 UTC, RafaelTaranto approved these changes

2021-11-17 14:30 UTC, merged