refactor: handle UI translations errors
lamassu/lamassu-machine pull request #653
Opened 2021-08-10 22:05 UTC by josepfo

2021-08-10 22:06 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Encapsulate UI translations inside a function with proper error handling](https://trello.com/c/cSQTsUeA/891-encapsulate-ui-translations-inside-a-function-with-proper-error-handling)

2021-08-18 13:26 UTC, RafaelTaranto requested changes

2021-08-18 13:26 UTC, RafaelTaranto commented on ui/src/app.js
> +        translate('This could take a few moments.'))
This can become a oneliner, translate alone on the second line is a bit confusing with the extra parenthesis

2021-08-18 13:26 UTC, RafaelTaranto commented on ui/src/app.js
> +        translate('Connected. Waiting for ticker.'))
same as above

2021-08-18 13:26 UTC, RafaelTaranto commented on ui/src/app.js
> +function translate (data, fetch) {
rename fetch to fetchArgs

2021-08-30 10:50 UTC, RafaelTaranto approved these changes

2021-09-07 16:03 UTC, joshmh commented on ui/src/app.js
> +    console.error('Error while translating: ', error)
Should this return the original, untranslated string? Or translated into default, English?

2021-09-24 09:30 UTC, merged