feat: ping time internet quality measurement
lamassu/lamassu-machine pull request #655
Opened 2021-08-13 14:40 UTC by josepfo

2021-08-13 14:40 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Backport "Ping time"](https://trello.com/c/IkxRswk9/912-backport-ping-time)

2021-08-16 12:41 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Backport "Ping time"](https://trello.com/c/IkxRswk9/912-backport-ping-time)

2021-09-01 21:16 UTC, chaotixkilla requested changes

2021-09-01 21:16 UTC, chaotixkilla commented on lib/ping.js
> +module.exports = { pingRepository, checkDownloadSpeed }
Missing newline at end of file

2021-09-07 14:08 UTC, RafaelTaranto approved these changes

2021-09-07 15:41 UTC, merged