feat: paper wallet only from server
lamassu/lamassu-machine pull request #661
Opened 2021-09-04 23:18 UTC by josepfo

2021-09-05 17:56 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Move paper wallet-only printing to the admin, support the rest of coins](https://trello.com/c/9Li42AQV/934-move-paper-wallet-only-printing-to-the-admin-support-the-rest-of-coins)

2021-09-09 03:11 UTC, chaotixkilla approved these changes

2022-02-04 16:59 UTC, chaotixkilla requested changes

2022-02-04 16:59 UTC, chaotixkilla commented on lib/brain.js
> +const COINS_SUPPORTING_PAPER_WALLET = ['BTC', 'LTC', 'BCH']
Instead of the hardcoded array here, consider replacing with the `getPaperWalletSupportiveCoins()` function we spoke about

2022-02-11 18:00 UTC, chaotixkilla approved these changes

2022-02-14 16:08 UTC, merged