Fix: ping time errors on unpaired clients
lamassu/lamassu-machine pull request #703
Opened 2021-10-22 00:12 UTC by josepfo

2021-10-22 00:19 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Undefined type errors from ping time feature on unpaired machines](https://trello.com/c/8t417kBq/1030-undefined-type-errors-from-ping-time-feature-on-unpaired-machines)

2021-10-24 16:11 UTC, chaotixkilla approved these changes

2021-11-02 13:48 UTC, RafaelTaranto requested changes

2021-11-02 13:48 UTC, RafaelTaranto commented on lib/brain.js
> +        return _.isNumber(speedValue) && _.isFinite(speedValue)
Can't you just do:

```js
_.isFinite(_.toNumber(x.speedValue))

```

2021-11-12 10:07 UTC, merged