feat: backport taproot support
lamassu/lamassu-machine pull request #708
Opened 2021-11-03 14:31 UTC by josepfo

2021-11-03 14:32 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Taproot readiness](https://trello.com/c/xnxFA7tJ/1057-taproot-readiness)

2021-11-05 15:12 UTC, SiIky requested changes
Just the `base58Opts` variable.

2021-11-05 15:42 UTC, SiIky approved these changes
LGTM

2021-11-11 15:11 UTC, RafaelTaranto approved these changes

2021-11-12 10:06 UTC, merged