Add Fixed Fee setting for cash-out transactions
lamassu/lamassu-machine pull request #835
Opened 2022-08-17 15:42 UTC by siiky

2022-10-06 09:44 UTC, RafaelTaranto requested changes

2022-10-06 09:44 UTC, RafaelTaranto commented on ui/src/app.js
> +  }
This needs to get built, `npm run build`

2022-10-06 09:44 UTC, RafaelTaranto commented on lib/brain.js
> -  return this.fastUpdateTx(billUpdate)
Yeah, it's time to remove this. But we need to thing of something for this scenario in specific. Maybe throw a error, maybe do it generically on the machine if versions are too far apart. 

@CrypticaScriptura What do you think?

2022-10-06 09:44 UTC, RafaelTaranto commented on lib/tx.js
> +    cryptoAtoms: truncateCrypto(toCrypto(mergedTx, oldTx.fiat.add(updateTx.fiat || 0).minus(fee)), cryptoCode),
Shouldn't we be adding the fee?

2022-10-07 12:46 UTC, siiky commented on lib/tx.js
> +    cryptoAtoms: truncateCrypto(toCrypto(mergedTx, oldTx.fiat.add(updateTx.fiat || 0).minus(fee)), cryptoCode),
Yeah, nice catch!

2022-10-10 09:21 UTC, merged

2022-10-10 12:46 UTC, CrypticaScriptura commented on lib/brain.js
> -  return this.fastUpdateTx(billUpdate)
Likely time for a version discrepancy screen on the machine that prevents operation entirely if the particular machine's version is sufficiently distant from that of the server. Would be preferable if reserved for major version releases (as this is, v9.0.0).