Add dynamic blacklisted address message
lamassu/lamassu-machine pull request #850
Opened 2022-10-06 18:08 UTC by chaotixkilla

2022-10-14 09:42 UTC, siiky approved these changes

2022-10-17 13:09 UTC, siiky approved these changes

2022-12-14 09:33 UTC, RafaelTaranto requested changes

2022-12-14 09:33 UTC, RafaelTaranto commented on ui/html/suspicious-address.html
>        </p>
Isn't leaving the message here going to double the "This address..." key on the translations? Might as well remove the text and js-i18n from here.

2022-12-19 15:09 UTC, siiky commented on ui/html/suspicious-address.html
>        </p>
I didn't see a duplicated message while trying the feature out, but maybe I misunderstood the scenario.

2022-12-26 10:47 UTC, closed without merging